### ISSUE TITLE
Modification of second argument

### ISSUE THREAD

**Issue by gezeta-id** [jesusgm/deepMerge#2]
There is a problem here on [line 48 of the code](https://github.com/jesusgm/deepmergefn/blob/cae1a39319abbb67aba291ff0bb1f5a7e0ddc901/index.js#L48).

Doing that means that, after calling your `deepMerge` function, `obj2` _will_ be modified. It will in fact be equal to `result`. This is a _very bad_ idea, and I would consider it a bug in the library.

**Comment by jesusgm** [comment]
Fixed in #1 solution
